In [1]:
import numpy as np
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [2]:
data = np.array([[1,2,3,4,5],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]])

In [ ]:
#StandardScaler es para escalar los datos a una media de 0 y una desviacion estadar de -1
#fit_transform es para ajustar el escalador a los datos y luego transformarlos 
# es decir 

scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)
print(scaled_data)

[[-1.35411306 -1.35411306 -1.35411306 -1.35411306 -1.35411306]
 [-0.76536825 -0.76536825 -0.76536825 -0.76536825 -0.76536825]
 [-0.02943724 -0.02943724 -0.02943724 -0.02943724 -0.02943724]
 [ 0.70649377  0.70649377  0.70649377  0.70649377  0.70649377]
 [ 1.44242478  1.44242478  1.44242478  1.44242478  1.44242478]]


In [4]:
#MinMaxScaler es usado para escalar los datos a un rango especifico, por defecto es entre 0 y 1

min_max_scaler = MinMaxScaler()
normalized_data = min_max_scaler.fit_transform(data)
print(normalized_data)

[[0.         0.         0.         0.         0.        ]
 [0.21052632 0.21052632 0.21052632 0.21052632 0.21052632]
 [0.47368421 0.47368421 0.47368421 0.47368421 0.47368421]
 [0.73684211 0.73684211 0.73684211 0.73684211 0.73684211]
 [1.         1.         1.         1.         1.        ]]
